name: Monitor Interpelli Alessandria

on:
  schedule:
    - cron: "*/5 * * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:

  monitor:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Test DNS
        run: |
          echo "DNS GitHub:"
          nslookup servizi.istruzionepiemonte.it || true
      
          echo ""
          echo "Google DNS:"
          nslookup servizi.istruzionepiemonte.it 8.8.8.8 || true
      
          echo ""
          echo "Cloudflare DNS:"
          nslookup servizi.istruzionepiemonte.it 1.1.1.1 || true
    
      - name: Run monitor
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python monitor.py

      - name: Save state
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add seen.json

          git diff --cached --quiet || git commit -m "Update seen interpelli"

          git push
